export { default as LandingPage } from "./landingPage";
export { default as LoginPage } from "./loginPage";
export { default as RegisterPage } from "./registerPage";
export { default as FeedPage } from "./feedPage";
export { default as DashboardPage } from "./dashboardPage";
export { default as ProfilePage } from "./profilePage";
export { default as ActivityPage } from "./activityPage";
export { default as LeaderboardPage } from "./leaderboardPage";
export { default as FriendPage } from "./friendPage";
